.PHONY: clean All

All:
	@echo "----------Building project:[ Practice_Miscellaneous - Debug ]----------"
	@cd "Practice_Miscellaneous" && "$(MAKE)" -f  "Practice_Miscellaneous.mk"
clean:
	@echo "----------Cleaning project:[ Practice_Miscellaneous - Debug ]----------"
	@cd "Practice_Miscellaneous" && "$(MAKE)" -f  "Practice_Miscellaneous.mk" clean
